### ISSUE TITLE
Dashed rectangles weird behavior

### ISSUE THREAD

**Issue by jairbubbles** [yass007/FASTBuildMonitor#1]
When zoming out dashed rectangles appear while they should not.
For instance here is a dashed rectangle :
![2016-08-24 09_17_20-clipboard](https://cloud.githubusercontent.com/assets/15875066/17921721/a3d475f8-69db-11e6-9a38-c52221344840.png)
But when zooming in it's empty: 
![2016-08-24 09_17_42-clipboard](https://cloud.githubusercontent.com/assets/15875066/17921720/a3d2c406-69db-11e6-8542-14d86477b429.png)

**Comment by yass007** [comment]
Thanks for reporting this issue!

**Comment by yass007** [comment]
Resolved in v0.95
It would be nice If you can test it with your repro-case and confirm it works now.

**Comment by jairbubbles** [comment]
Works fine ! Thank you
