### ISSUE TITLE
Follow-up of "float.Parse uses the current system culture by default"

### ISSUE THREAD

**Issue by G4m4** [yass007/FASTBuildMonitor#12]
The issue #11 actually affected two different places in exactly the same way; ExecuteCommandProgressStatus() which has been fixed, but also ExecuteCommandGraph() where it should be:

`float value = float.Parse(tokens[CommandArgumentIndex.GRAPH_COUNTER_VALUE], CultureInfo.InvariantCulture );`

**Comment by yass007** [comment]
Thanks for the note! Fixed in v1.021.
