### ISSUE TITLE
FASTBuildMonitor (either standalone or VSIX) does not show any activity

### ISSUE THREAD

**Issue by lucianm** [yass007/FASTBuildMonitor#13]
Hi there,

I just wanted to give FASTBuildMonitor a go, using FBuild 0.92, and I'm not able to see any activity in the GUI during FBuilds started with the "-monitor" switch. I do see however, that a proper monitoring log file is being written to %TEMP%\FastBuild\FastBuildLog.log which is permanently in use by the monitor process and can not be deleted, only after closing the monitor. This indicates that the monitor really tries to parse the log file, but it does not show any information in the GUI. Which, by the way, is very stubborn in immediately switching any tab to the first one, one second after clicking the settings tab or the filter tab.
I just followed the instructions in the README to install it, even built it with VS2015, the behaviour is the same. Anything I'm doing wrong?

**Comment by yass007** [comment]
Since I pushed a new parsing fix in v1.021. Could you please try and let me know if you still get the issue?

**Comment by lucianm** [comment]
Hi Yassine,
sorry for stopping by so late, so I tried your newest release and the issues seem to be gone now, thank you.
Cheers ;)
