### ISSUE TITLE
Monitor does not (always) show the current build

### ISSUE THREAD

**Issue by jairbubbles** [yass007/FASTBuildMonitor#15]
It was working correctly until today.
I'm currently building (with -monitor) but the last build is being displayed:
![image](https://user-images.githubusercontent.com/15875066/27274400-605b49ee-54d3-11e7-94fe-89325eb13c27.png)
Is there a log file somewhere to help you out?

**Comment by yass007** [comment]
Very odd!
With -monitor FASTBuild is supposed to write build events to **C:\Users\<your_user_name>\AppData\Local\Temp\FastBuild**
You could try delete that file and try again see if it is regenerated.

Have you switched FBuild version recently?

**Comment by jairbubbles** [comment]
Now it's working correctly. I think we can close the issue. I'll reopen it if it happens again. Any logs that can be useful?

**Comment by yass007** [comment]
Unfortunately no other logs are available to diagnose this feature within FBuild.
Let me know if it occurs again and we'll dig a bit deeper.
Thanks!

**Comment by jairbubbles** [comment]
I didn't even check if the fbuild files were properly written... I make a very lousy tester 😄 . (We're using latest version (v0.93) with some tweaks)
