### ISSUE TITLE
Tooltips not always working

### ISSUE THREAD

**Issue by jairbubbles** [yass007/FASTBuildMonitor#4]
Since version 0.95 depending on the rectangle you're hovering the tooltip appears empty.
![2016-09-01 10_27_52-clipboard](https://cloud.githubusercontent.com/assets/15875066/18160674/c2da9d84-702e-11e6-8f30-c41dea643d08.png)

IIf I unzoom without moving the tooltip appears correctly.
![2016-09-01 10_30_19-scimitar engine durango vs2015 - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/15875066/18160752/1c75c968-702f-11e6-907a-23f36b5035d5.png)

**Comment by yass007** [comment]
Should be fixed now. Thanks for the report!
