### ISSUE TITLE
[Request] Add elapsed time on building task (purple)

### ISSUE THREAD

**Issue by jairbubbles** [yass007/FASTBuildMonitor#6]
Very minor but it will be nice to see already elapsed time on currently building task.
![2016-09-01 10_47_47-scimitar tool dll win64 vs2012 - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/15875066/18161296/a536ca20-7031-11e6-80d7-6d506c5b390b.png)

Thx !

**Comment by yass007** [comment]
Will be released with v0.97.
